global:
    scrape_interval: 10s
    evaluation_interval: 10s

scrape_configs:
    - job_name: redpanda
      static_configs:
          - targets:
                - redpanda-0:9644
      metrics_path: /public_metrics

alerting:
    alertmanagers:
        - scheme: http
          static_configs:
              - targets:
                    - alertmanager:9093

rule_files:
    - /etc/prometheus/alert-rules.yml
