{
 "title": "Kafka Consumer",
 "description": "Kafka Consumer Java client metrics",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "client_id",
    "label": "Client ID",
    "query": {
     "query": "label_values(kafka_consumer_app_info, client_id)"
    }
   },
   { "name": "env", "label": "Environment", "query": { "query": "label_values(env)" } },
   {
    "name": "consumer_group",
    "label": "Group ID",
    "query": {
     "query": "label_values(kafka_consumergroup_group_lag, group)"
    }
   },
   { "name": "topic", "label": "topic", "query": { "query": "label_values(topic)" } },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {
     "query": "label_values(kafka_consumer_app_info, hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Note\nThis dashboard requires a JMX agent reporting statistics from a Kafka Java consumer into Prometheus.\n\n⚠️ This dashboard has some sample thresholds, this example is not meant to fit all use cases nor is it meant for production. Think of it as a learning tool to help you become comfortable with the metrics and thresholding.\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Key metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Commit rate",
   "type": "timeseries",
   "description": "The number of commit calls per second .",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_coordinator_metrics_commit_rate  "
    }
   ]
  },
  {
   "title": "Average fetch throttle time",
   "type": "stat",
   "description": "The average time in ms a request was throttled by a broker.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_produce_throttle_time_avg  "
    }
   ]
  },
  {
   "title": "Failed auth rate",
   "type": "stat",
   "description": "Rate of failed authentication attempts\n",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_admin_client_admin_client_metrics_failed_authentication_rate  "
    }
   ]
  },
  {
   "title": "Rebalance rate per hour",
   "type": "timeseries",
   "description": "The number of total rebalance events per hour, both successful and unsuccessful rebalance attempts.",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_coordinator_metrics_rebalance_rate_per_hour"
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "process_cpu_seconds_total  " }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "jvm_memory_bytes_max" }
   ]
  },
  {
   "title": "JVM GC time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum[5m])"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Bytes consumed rate",
   "type": "timeseries",
   "description": "The average number of bytes consumed per second\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(kafka_consumer_consumer_fetch_manager_metrics_bytes_consumed_total[1m])"
    }
   ]
  },
  {
   "title": "Rate of records consumed",
   "type": "timeseries",
   "description": "The average number of records consumed per second.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(kafka_consumer_consumer_fetch_manager_metrics_records_consumed_total[1m])"
    }
   ]
  },
  {
   "title": "Bytes consumed rate per topic",
   "type": "timeseries",
   "description": "The average number of bytes consumed per topic per second.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_consumer_consumer_fetch_manager_metrics_bytes_consumed_total[1m])) by (topic)"
    }
   ]
  },
  {
   "title": "Rate of records consumed per topic",
   "type": "timeseries",
   "description": "The average number of records consumed per second per topic.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_consumer_consumer_fetch_manager_metrics_records_consumed_rate[1m]))by (topic)"
    }
   ]
  },
  {
   "title": "Consumer Fetch Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Fetch request rate",
   "type": "timeseries",
   "description": "The number of fetch requests per second.\n",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(kafka_consumer_consumer_fetch_manager_metrics_fetch_total[1m])"
    }
   ]
  },
  {
   "title": "Fetch size avg",
   "type": "timeseries",
   "description": "The average number of bytes fetched per request for a topic",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_fetch_manager_metrics_fetch_size_avg"
    }
   ]
  },
  {
   "title": "Fetch latency average",
   "type": "timeseries",
   "description": "The average time taken for a fetch request.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_fetch_manager_metrics_fetch_latency_avg"
    }
   ]
  },
  {
   "title": "Consumer Commit Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Commit latency average",
   "type": "timeseries",
   "description": "The average time taken for a commit request",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_coordinator_metrics_commit_latency_avg"
    }
   ]
  },
  {
   "title": "Commit rate",
   "type": "timeseries",
   "description": "The number of commit calls per second .",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_coordinator_metrics_commit_rate"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current connection count",
   "type": "timeseries",
   "description": "Number of simultaneous connections\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_metrics_connection_count"
    }
   ]
  },
  {
   "title": "Node response rate",
   "type": "timeseries",
   "description": "response rate per node\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_node_metrics_response_rate  "
    }
   ]
  }
 ]
}